apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: sinker
  labels:
    app: sinker
  annotations:
    wave.pusher.com/update-on-config-change: "true"  
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sinker
    spec:
      serviceAccountName: "sinker"
      containers:
      - name: sinker
        image: gcr.io/k8s-prow/sinker:v20190615-f3db6c682
        args:
        - --job-config-path=/etc/jobs
        - --dry-run=false
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: jobs
          mountPath: /etc/jobs
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: config
      - name: jobs
        configMap:
          name: jobs
