apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: tide
  labels:
    app: tide
  annotations:
    wave.pusher.com/update-on-config-change: "true"  
spec:
  replicas: 1 # Do not scale up.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tide
    spec:
      serviceAccountName: "tide"
      containers:
      - name: tide
        image: gcr.io/k8s-prow/tide:v20190307-bbad344
        args:
        - --dry-run=false
        - --job-config-path=/etc/jobs
        ports:
          - name: http
            containerPort: 8888
        volumeMounts:
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: jobs
          mountPath: /etc/jobs
          readOnly: true
      volumes:
      - name: oauth
        secret:
          secretName: oauth-token
      - name: config
        configMap:
          name: config
      - name: jobs
        configMap:
          name: jobs
