postsubmits:
  pusher/testing:
    - name: post-testing-build-docker
      max_concurrency: 10
      path_alias: github.com/pusher/testing
      agent: kubernetes
      branches:
        - master
      always_run: true
      decorate: true
      labels:
        preset-dind-enabled: "true"
        preset-quay-credentials: "true"
      spec:
        containers:
          - image: quay.io/pusher/builder:v20190801-3bf82c1
            name: build-docker
            command: ["/usr/local/bin/runner"]
            args:
              - make --directory=images push
            resources:
              requests:
                cpu: 1
                memory: 1Gi
            securityContext:
              privileged: true

    - name: post-testing-build-docker-pipeline
      max_concurrency: 10
      path_alias: github.com/pusher/testing
      agent: tekton-pipeline
      branches:
        - master
      always_run: true
      skip_report: false
      labels:
        preset-dind-enabled: "true"
        preset-quay-credentials: "true"
      pipeline_run_spec:
          pipelineRef:
            name: testing-post-builder-images
          resources:
          - name: testing
            resourceRef:
              name: PROW_IMPLICIT_GIT_REF
      trigger: "(?m)^/build docker-pipeline,?(\\s+|$)"
      rerun_command: "/build docker-pipeline"
