apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: needs-rebase
  namespace: default
  labels:
    app: needs-rebase
spec:
  minReplicas: 2
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: needs-rebase
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80
