presubmits:
  pusher/wave:
    - name: pull-wave-verify-generate
      max_concurrency: 10
      path_alias: github.com/pusher/wave
      agent: kubernetes
      always_run: true
      skip_report: false
      decorate: true
      spec:
        containers:
          - image: quay.io/pusher/kubebuilder-builder:v20190401-6a7e3ff
            name: verify-generate
            command: ["/usr/local/bin/runner"]
            args:
              - touch .env && make prepare-env-1.13 && make verify-generate
            resources:
              requests:
                cpu: 1
                memory: 1Gi
      trigger: "(?m)^/verify generate,?(\\s+|$)"
      rerun_command: "/verify generate"

    - name: pull-wave-verify-manifests
      max_concurrency: 10
      path_alias: github.com/pusher/wave
      agent: kubernetes
      always_run: true
      skip_report: false
      decorate: true
      spec:
        containers:
          - image: quay.io/pusher/kubebuilder-builder:v20190401-6a7e3ff
            name: verify-manifests
            command: ["/usr/local/bin/runner"]
            args:
              - touch .env && make prepare-env-1.13 && make verify-manifests
            resources:
              requests:
                cpu: 1
                memory: 1Gi
      trigger: "(?m)^/verify manifests,?(\\s+|$)"
      rerun_command: "/verify manifests"

    - name: pull-wave-lint
      max_concurrency: 10
      path_alias: github.com/pusher/wave
      agent: kubernetes
      always_run: true
      skip_report: false
      decorate: true
      spec:
        containers:
          - image: quay.io/pusher/kubebuilder-builder:v20190401-6a7e3ff
            name: lint
            command: ["/usr/local/bin/runner"]
            args:
              - touch .env && make prepare-env-1.13 && make lint
            resources:
              requests:
                cpu: 1
                memory: 1Gi
      trigger: "(?m)^/lint,?(\\s+|$)"
      rerun_command: "/lint"

    - name: pull-wave-test-ginkgo
      max_concurrency: 10
      path_alias: github.com/pusher/wave
      agent: kubernetes
      always_run: true
      skip_report: false
      decorate: true
      spec:
        containers:
          - image: quay.io/pusher/kubebuilder-builder:v20190401-6a7e3ff
            name: test-ginkgo
            command: ["/usr/local/bin/runner"]
            args:
              - touch .env && make prepare-env-1.13 && make test
            resources:
              requests:
                cpu: 1
                memory: 1Gi
      trigger: "(?m)^/test ginkgo,?(\\s+|$)"
      rerun_command: "/test ginkgo"

    - name: pull-wave-build-docker
      max_concurrency: 10
      path_alias: github.com/pusher/wave
      agent: kubernetes
      always_run: false
      skip_report: false
      decorate: true
      labels:
        preset-dind-enabled: "true"
      spec:
        containers:
          - image: quay.io/pusher/builder:v20190401-6a7e3ff
            name: build-docker
            command: ["/usr/local/bin/runner"]
            args:
              - touch .env; # No config necessary
              - TAGS=pull-${PULL_NUMBER},${PULL_PULL_SHA}
              - PUSH_TAGS=${TAGS}
              - make docker-build docker-tag docker-push
            resources:
              requests:
                cpu: 1
                memory: 1Gi
            securityContext:
              privileged: true
      trigger: "(?m)^/build docker,?(\\s+|$)"
      rerun_command: "/build docker"
