apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: deck
  labels:
    app: deck
  annotations:
    wave.pusher.com/update-on-config-change: "true"
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: deck
    spec:
      serviceAccountName: "deck"
      terminationGracePeriodSeconds: 30
      containers:
        - name: deck
          image: gcr.io/k8s-prow/deck:v20190409-ef11deceb
          args:
            - --tide-url=http://tide.default.svc.cluster.local/
            - --hook-url=http://hook.default.svc.cluster.local:8888/plugin-help
            - --job-config-path=/etc/jobs
            - --spyglass=true
            - --oauth-url=/github-login
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/config
              readOnly: true
            - name: jobs
              mountPath: /etc/jobs
              readOnly: true
            - name: extensions
              mountPath: /static/extensions
              readOnly: true
            - name: oauth-config
              mountPath: /etc/github
              readOnly: true
            - name: cookie-secret
              mountPath: /etc/cookie
              readOnly: true
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8081
        initialDelaySeconds: 3
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: /healthz/ready
          port: 8081
        initialDelaySeconds: 10
        periodSeconds: 3
        timeoutSeconds: 3
      volumes:
        - name: config
          configMap:
            name: config
        - name: jobs
          configMap:
            name: jobs
        - name: extensions
          configMap:
            name: extensions
        - name: oauth-config
          secret:
              secretName: github-oauth-config
        - name: cookie-secret
          secret:
              secretName: cookie-secret
