presubmits:
  pusher/faros:
    - name: pull-faros-verify-generate
      max_concurrency: 10
      path_alias: github.com/pusher/faros
      agent: kubernetes
      always_run: true
      skip_report: false
      decorate: true
      spec:
        containers:
          - image: golang:1.12-stretch
            name: verify-generate
            command: ["/bin/sh", "-c"]
            args:
              - touch .env && make prepare-env-1.13 && make verify-generate
            resources:
              requests:
                cpu: 1
                memory: 1Gi
      trigger: "(?m)^/verify generate,?(\\s+|$)"
      rerun_command: "/verify generate"

    - name: pull-faros-verify-manifests
      max_concurrency: 10
      path_alias: github.com/pusher/faros
      agent: kubernetes
      always_run: true
      skip_report: false
      decorate: true
      spec:
        containers:
          - image: golang:1.12-stretch
            name: verify-manifests
            command: ["/bin/sh", "-c"]
            args:
              - touch .env && make prepare-env-1.13 && make verify-manifests
            resources:
              requests:
                cpu: 1
                memory: 1Gi
      trigger: "(?m)^/verify manifests,?(\\s+|$)"
      rerun_command: "/verify manifests"

    - name: pull-faros-lint
      max_concurrency: 10
      path_alias: github.com/pusher/faros
      agent: kubernetes
      always_run: true
      skip_report: false
      decorate: true
      spec:
        containers:
          - image: golang:1.12-stretch
            name: lint
            command: ["/bin/sh", "-c"]
            args:
              - touch .env && make prepare-env-1.13 && make lint
            resources:
              requests:
                cpu: 1
                memory: 1Gi
      trigger: "(?m)^/lint,?(\\s+|$)"
      rerun_command: "/lint"

    - name: pull-faros-test-ginkgo
      max_concurrency: 10
      path_alias: github.com/pusher/faros
      agent: kubernetes
      always_run: true
      skip_report: false
      decorate: true
      spec:
        containers:
          - image: golang:1.12-stretch
            name: test-ginkgo
            command: ["/bin/sh", "-c"]
            args:
              - touch .env && make prepare-env-1.13 && make test-ginkgo
            resources:
              requests:
                cpu: 1
                memory: 1Gi
      trigger: "(?m)^/test ginkgo,?(\\s+|$)"
      rerun_command: "/test ginkgo"
