presubmits:
  pusher/faros:
    - name: pull-faros-verify-generate
      max_concurrency: 10
      path_alias: github.com/pusher/faros
      agent: kubernetes
      always_run: true
      skip_report: false
      decorate: true
      spec:
        containers:
          - image: quay.io/pusher/kubebuilder-builder:v20190401-6a7e3ff
            name: verify-generate
            command: ["/usr/local/bin/runner"]
            args:
              - touch .env && make prepare-env-1.13 && make verify-generate
            resources:
              requests:
                cpu: 1
                memory: 1Gi
      trigger: "(?m)^/test (?:.*? )?(verify-generate|all)(?: .*?)?$"
      rerun_command: "/test verify-generate"

    - name: pull-faros-verify-manifests
      max_concurrency: 10
      path_alias: github.com/pusher/faros
      agent: kubernetes
      always_run: true
      skip_report: false
      decorate: true
      spec:
        containers:
          - image: quay.io/pusher/kubebuilder-builder:v20190401-6a7e3ff
            name: verify-manifests
            command: ["/usr/local/bin/runner"]
            args:
              - touch .env && make prepare-env-1.13 && make verify-manifests
            resources:
              requests:
                cpu: 1
                memory: 1Gi
      trigger: "(?m)^/test (?:.*? )?(verify-manifests|all)(?: .*?)?$"
      rerun_command: "/test verify-manifests"

    - name: pull-faros-lint
      max_concurrency: 10
      path_alias: github.com/pusher/faros
      agent: kubernetes
      always_run: true
      skip_report: false
      decorate: true
      spec:
        containers:
          - image: quay.io/pusher/kubebuilder-builder:v20190401-6a7e3ff
            name: lint
            command: ["/usr/local/bin/runner"]
            args:
              - touch .env && make prepare-env-1.13 && make lint
            resources:
              requests:
                cpu: 1
                memory: 1Gi
      trigger: "(?m)^/test (?:.*? )?(lint|all)(?:.*? )?$"
      rerun_command: "/test lint"

    - name: pull-faros-test-1.13
      max_concurrency: 10
      path_alias: github.com/pusher/faros
      agent: kubernetes
      always_run: true
      skip_report: false
      decorate: true
      spec:
        containers:
          - image: quay.io/pusher/kubebuilder-builder:v20190401-6a7e3ff
            name: test-ginkgo
            command: ["/usr/local/bin/runner"]
            args:
              - touch .env && make prepare-env-1.13 && make test
            resources:
              requests:
                cpu: 3
                memory: 2Gi
      trigger: "(?m)^/test (?:.*? )?(1.13|all)(?: .*?)?$"
      rerun_command: "/test 1.13"

    - name: pull-faros-test-1.12
      max_concurrency: 10
      path_alias: github.com/pusher/faros
      agent: kubernetes
      always_run: true
      skip_report: false
      decorate: true
      spec:
        containers:
          - image: quay.io/pusher/kubebuilder-builder
            name: test-ginkgo
            command: ["/usr/local/bin/runner"]
            args:
              - touch .env && make prepare-env-1.12 && SKIP_DRY_RUN_TESTS=true make test
            resources:
              requests:
                cpu: 3
                memory: 2Gi
      trigger: "(?m)^/test (?:.*? )?(1.12|all)(?: .*?)?$"
      rerun_command: "/test 1.12"

    - name: pull-faros-test-1.11
      max_concurrency: 10
      path_alias: github.com/pusher/faros
      agent: kubernetes
      always_run: true
      skip_report: false
      decorate: true
      spec:
        containers:
          - image: quay.io/pusher/kubebuilder-builder
            name: test-ginkgo
            command: ["/usr/local/bin/runner"]
            args:
              - touch .env && make prepare-env-1.11 && SKIP_DRY_RUN_TESTS=true make test
            resources:
              requests:
                cpu: 3
                memory: 2Gi
      trigger: "(?m)^/test (?:.*? )?(1.11|all)(?: .*?)?$"
      rerun_command: "/test 1.11"

    - name: pull-faros-build-docker
      max_concurrency: 10
      path_alias: github.com/pusher/faros
      agent: kubernetes
      always_run: false
      skip_report: false
      decorate: true
      labels:
        preset-dind-enabled: "true"
      spec:
        containers:
          - image: quay.io/pusher/builder:v20190401-6a7e3ff
            name: build-docker
            command: ["/usr/local/bin/runner"]
            args:
              - touch .env; # No config necessary
              - TAGS=pull-${PULL_NUMBER},${PULL_PULL_SHA}
              - PUSH_TAGS=${TAGS}
              - make docker-build docker-tag docker-push
            resources:
              requests:
                cpu: 1
                memory: 1Gi
            securityContext:
              privileged: true
      trigger: "(?m)^/build (?:.*? )?(docker|all)(?: .*?)?$"
      rerun_command: "/build docker"
