triggers:
  - repos:
      - pusher/testing
      - pusher/faros
      - pusher/wave
    trusted_org: pusher
    only_org_members: true
  - repos:
      - pusher/oauth2_proxy
    trusted_org: oauth2_proxy
    only_org_members: true

plugins:
  pusher/testing:
    - size
    - lgtm
    - cat
    - label
    - dog
    - trigger
    - yuks
    - assign
  pusher/faros:
    - size
    - lgtm
    - cat
    - label
    - dog
    - trigger
    - yuks
    - assign
  pusher/wave:
    - size
    - lgtm
    - cat
    - label
    - dog
    - trigger
    - yuks
    - assign
