apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: horologium
  labels:
    app: horologium
spec:
  replicas: 1 # Do not scale up.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: horologium
    spec:
      serviceAccountName: "horologium"
      terminationGracePeriodSeconds: 30
      containers:
      - name: horologium
        image: gcr.io/k8s-prow/horologium:v20190307-bbad344
        args:
        - --job-config-path=/etc/jobs
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: jobs
          mountPath: /etc/jobs
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: config
      - name: jobs
        configMap:
          name: jobs
