apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: plank
  labels:
    app: plank
  annotations:
    wave.pusher.com/update-on-config-change: "true"
spec:
  replicas: 1 # Do not scale up.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plank
    spec:
      serviceAccountName: "plank"
      containers:
      - name: plank
        image: gcr.io/k8s-prow/plank:v20190615-f3db6c682
        args:
        - --dry-run=false
        - --job-config-path=/etc/jobs
        volumeMounts:
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: jobs
          mountPath: /etc/jobs
          readOnly: true
      volumes:
      - name: oauth
        secret:
          secretName: oauth-token
      - name: config
        configMap:
          name: config
      - name: jobs
        configMap:
          name: jobs
