apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: quay-docker-config
  namespace: default
spec:
  encryptedData:
    config.json: AgCUdQ79+U0TesKq+h4ivg6yYvHjJVtT1p453vf1BtX1/BOurov/FlNcP7zxJ6sbOFU59noxgUOa2soWw1FDoj50g4xOxsZzXsBxpuNVDLoavYGdSoIZFzZhKNcCs9XManCPtWKsI1mCqPZqE/bVnY/iHMkxVEFR3zW1a3xRa0U6WoZaZsddZfn5Sz0u/k6iFVkrIHAktXCCKMQG4DN23blokJFg+ymFLtLN6J1ssKxKJezRgAoE+oTYvIOOZ7ic8QygBZsoLiVjC3xt2b/dbWpRUA6rppU3k8UWeYyU7xob8HHHJz2tsWJSAYRU3WCc4T5OGZOTqjYpucQDdYU1/LdrkCyDMT8QBHLII/Yg0fJAVxbFIzs2ch0iJohzCvd1yMXk4WeXqTW7t/Yj1Tic2hVS/nCBNFCWdtCi6ZT09TXPq+JgJ5M/lbSXWUEgNwJ9g+Zuu8nxFxWKhPraLcxWfzLirlCi5IOxkjwAt90POiqiWeNUSciOzJPzzHgmK5eG7WYGF9VzWTWasHZWDfEVQkqXH+LzlSznM9I0iaHHqycBZ/h3NIfOUfXYcKxiBboRNX0ENMm4/ooqV/j/IIp1aSxn/53tjNFWTzTzzWllh5bMkafjE5VK9I/DANsOfkLL9zeXvyKjAOWsT46PKvk/RQUeshuCqRoHptrwgyi8rm4f96TKLX6UIvruD0x1LjCmD2P6zZc9ifJ9CxqwjdzYR89eeo3kJVB6Hlqrj8oZ/ZNedIzuz/QRqykTqcqaaNVJ8h5FJ7G2kVehTUW5zUIQRVRjuPs6afuetZLLo83qAuu3brwXUZzyScRRAeUhSX5cf4LNUDQIDy24GxOuxihiMTixbfC0nzrHIPg1HqQlfSh64Kq1A9IcfzvmQRr804lXU79iA3QD0bJg43LecF7iDE0/lSanLgN2eCFCnVfMVSX0XPvlGYW2isg=

