apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth-token
  namespace: default
spec:
  encryptedData:
    oauth: AgCJOHIKIGuW4NOeSHtuAsFu8LDwnAitimTpDXLQ9ZGaMzZROT7vMmGkKGkxT0jXN3/VbEHXbHdoM1iStwrRmSXSQiFzHM+hbKNJ2jwQohGxhgHyjLUbJvDvYKEaHBDaNJKeCJfU1EgDPHtgw02YGlKtXtzYMJ7LpdVLNtfQFyQtJ+j6WmRnX/TBb668tpF/nUW51FyoEqOr9fIktoNuX0p13JzUSyEdjylsQkkHGW0ADmkPec2rBFxbq39BGDPRcTJCiqIrnoHPE4UOa4U22AwcZyfB0w26aC64ICsVOO2icwt+dSun05CB65DzQTSkNf8eKkLL+ljzcoRy/wHs+4rmLudGmSEmVMucpNSnn16dvmxQOvDk2DRP1DdFTlztRgKjPjVH2SpYsRLWQhYLLIjC9ThVvZuweKbhbiok+0+gRKO88rYSx8gyjZjOmxNXfr3Edld8qgKPAS+rXi0Hdtyoiyy1I7pVBmPOFzAQkUqLOGzHXKsXny5WuzQr5KQAjA8V7MvY0x84kJXirePUQROkAI2dhU573oVkD9vzeuBumfsqxV5JmG5PSNnhlEtt6qR0yIynAbOJSGU9++AtQpFm51LMdRBrMo9q08Yh6pd20vy7TQh+w7Z+XfmxFl1VdwalHMGFs2iMZ5sBq3Y035gmFl2dhSm7JDt8HcGffkIuSg0kfFu10HXWnX6Ld9wIJCNpwaMjmgu/GFR8/HWMEdgU/zHmRrAM8EihLOzS7d7GzfZP1O4y+m1fLw==

