apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hmac-token
  namespace: default
spec:
  encryptedData:
    hmac: AgCK32zttoKD3FC86/FpD/FxSkaiQHZBjZiN+YJ+xB18E7w3u9pkmkFNS/AGWH/meJmThZrPXA+I+sBK5qDhNcSKZj4SOidNAF+t20TfvanaIrpkjfP2Ro8GiTfmESpb4n+IGNHaBS3XOazNucUutCqNg7223+3sEMCWDSGHkUKcjNo3720nV3m2qoSoaeTktbxN193EuLD7WsyMq7KbiaC6kGCHaCFmd4/SuMbPceYVKfL5pvOGd6lizBR2LZmYbOz/FHSUQ763+czu6ruk5cAZcKDqr40imnEjLsgAdIFlZUphdVQ/nkQPADkxoGCVtnhKy8MZ8OlYTpYSFi7lU2kqVOf4Mj0PdJWbmSqNMSUrH5M58lL54R4ex8HmWl+JXz50RqC/LBP0SV6Y/opYILv1GY+AQ3DIh1O2KpU6JsSdUb+2C81UHH6dh+I/67voND/s06kkAqrqLjdn0MWVPoBgN+iHoB30VRyEnbdjujLsLBfiWA0VkJ6TRUZSVZ5xzM/fyH7uj+rvyK5RK6hjzyyRihFcF7W6pFQwcOVRA9x7ra/StjHN+FmON4s7U35pgEjmBUwtT4pF/e0g1YqR9q4GsR0GW1nkYcADuD8PaKqBrKR7DsCqImsmaOnXBG93QAefnE9RGPNFTPt0KKjFmdUA/3eQZmFFl/gP6KbSyjOmjQZHH3KHIh0wA3VOaBy6JRN9CaStXKfdek0r2gw1h1YlWT/ok6wQErZFrF3/GpI=
