apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-config
  namespace: default
spec:
  encryptedData:
    config.json: AgBZVTR8p2mu0vHZk0o1rWQYTSjS5vFigiuyG7xYKI81qejFqkUFICiIXPNs+LmBq0uAk0DjZIm8Vmc4RtqGRNS9ZLFkt1sFrfMlSQJKPw8wdyA5sXJE5OBiVwm6Az5MobUJH3rNQo7qvQqCY2ug4FRNc+gd4mPsfgQc5H+/okhqAiKPMSuz34WOZ4hyy3JAIowvVr4Qzpi2i7vA7hYHdq2VPEurfoo38CfJjt2Ec8omZlB2qqGY+TLGHXXAs6CjL7C0xN7+HjoOSUWeCHJiWU9ZCtefHZ8X/G8u4mp4k8t7BFrBJ4LL241n67brQH/Y5aCBDdevSP726G/uRcmxeQzJMRDcGmRwU/SU8zRKl57wuF1p62cDk5vP+DSRS2s5yRe1iNo9OhZyV2tzp4v79wU22ffDqFyhVf1fWUp13KSmQZM+ZslSAowwFpwUr4IOEiMkughvt2ax82UyKmV1iGJvZkDtfhpX+5ykxzX7YlGvXAiZCLRBKGYU39zTq+h08mkBrn3GSugQ1xv2yEA0VdBcsxpKwD6TUT8ukCnYcPGXFGuNlwihqc3uYwcFvl/hExcRZpk0kTcBfaz+yDizpQn5XAoEzXbo48TOV4ETnZg77WgwSHA8SdPp5lLYO22x8YqwkcumalajjIbqutVvqpLGtddz6CLRJ5SB4beteVxpZnNwDSErc0AGG9+DSq67N67bVQGsFRZ+R3FEhuUGiQzeP1D7ERLwS/ytC3KUZcvsSXnO7P9MQAE6fnMBpPUz9TMSIXbWrvWYZ/BJmffg4CpOlAQXPYeCSRFZ9gEKh4taGrhSUoGuxmxPZdEjIHfvBL7v8D3SfjxD8/e0+wxP8GiKCbPQDO5/YYhxH/p7VqL2s0G9ruQRB7SE4WIFuaMxiSaJ398n5L4bHn9CXBE3VWjqcLlsZBVIAKtLlJb7vGUv511Ux4qZDQtg91K/fJCURve00fcBTDGCsOEhWGkL3aWf25NjzMGRuJkQXYlRiLovV4HtQIhm6neSxCwlG3M05HK45BQQRIpkyBkayOJHYA6x7es5T96qnABoQe6EtLtNDi6VJl9/J4gIed24miSAIhneVSLrE2NK9nd0tS6wdbCbezGGqRIsdYi76owUVUhuSE7kNZduTVYi
  template:
    metadata:
      creationTimestamp: null
      name: docker-config
      namespace: default
    type: Opaque
status: {}

