apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: testing-pull-builder-images
spec:
  resources:
  - name: testing
    type: git
  params:
  - name: PULL_NUMBER
    description: GitHub pull request number
  - name: PULL_PULL_SHA
    description: Git SHA for the commit under test
  tasks:
  - name: build-builder
    taskRef:
      name: testing-build-image
    resources:
      inputs:
      - name: testing
        resource: testing
    params:
    - name: image
      value: builder
    - name: DOCKER_IN_DOCKER_ENABLED
      value: "true"
    - name: VERSION
      value: pull-${params.PULL_NUMBER}
    - name: TAGS
      value: pull-${params.PULL_NUMBER},${params.PULL_PULL_SHA}

  - name: build-golang-builder
    runAfter: [build-builder]
    taskRef:
      name: testing-build-image
    resources:
      inputs:
      - name: testing
        resource: testing
    params:
    - name: image
      value: golang-builder
    - name: DOCKER_IN_DOCKER_ENABLED
      value: "true"
    - name: VERSION
      value: pull-${params.PULL_NUMBER}
    - name: TAGS
      value: pull-${params.PULL_NUMBER},${params.PULL_PULL_SHA}

  - name: build-kubebuilder-builder
    runAfter: [build-golang-builder]
    taskRef:
      name: testing-build-image
    resources:
      inputs:
      - name: testing
        resource: testing
    params:
    - name: image
      value: kubebuilder-builder
    - name: DOCKER_IN_DOCKER_ENABLED
      value: "true"
    - name: VERSION
      value: pull-${params.PULL_NUMBER}
    - name: TAGS
      value: pull-${params.PULL_NUMBER},${params.PULL_PULL_SHA}

  - name: build-python-builder
    runAfter: [build-builder]
    taskRef:
      name: testing-build-image
    resources:
      inputs:
      - name: testing
        resource: testing
    params:
    - name: image
      value: python-builder
    - name: DOCKER_IN_DOCKER_ENABLED
      value: "true"
    - name: VERSION
      value: pull-${params.PULL_NUMBER}
    - name: TAGS
      value: pull-${params.PULL_NUMBER},${params.PULL_PULL_SHA}

  - name: build-admin-builder
    runAfter: [build-builder]
    taskRef:
      name: testing-build-image
    resources:
      inputs:
      - name: testing
        resource: testing
    params:
    - name: image
      value: admin-builder
    - name: DOCKER_IN_DOCKER_ENABLED
      value: "true"
    - name: VERSION
      value: pull-${params.PULL_NUMBER}
    - name: TAGS
      value: pull-${params.PULL_NUMBER},${params.PULL_PULL_SHA}

  - name: build-clonerefs
    taskRef:
      name: testing-build-image
    resources:
      inputs:
      - name: testing
        resource: testing
    params:
    - name: image
      value: clonerefs
    - name: DOCKER_IN_DOCKER_ENABLED
      value: "true"
    - name: VERSION
      value: pull-${params.PULL_NUMBER}
    - name: TAGS
      value: pull-${params.PULL_NUMBER},${params.PULL_PULL_SHA}
