job_template: &job_template
  max_concurrency: 10
  path_alias: github.com/pusher/prom-rule-reloader
  agent: kubernetes
  always_run: true
  skip_report: false
  decorate: true
  branches:
    - master
    # Abuse Prow to make it run on tag pushes like v1.2.3 and v1.2.3-rc1
    - ^v?\d+\.\d+\.\d+(-rc\d+)?$

container_template: &container_template
  image: quay.io/pusher/golang-builder:v20190404-3ebb4c5
  name: runner
  command: ["/usr/local/bin/runner"]

postsubmits:
  pusher/faros:
    - name: post-prom-rule-reloader-build-docker
      <<: *job_template
      labels:
        preset-dind-enabled: "true"
        preset-quay-credentials: "true"
      spec:
        containers:
          - <<: *container_template
            args:
              - touch .env; # No config necessary
              - TAGS=${PULL_BASE_REF},${PULL_BASE_SHA},latest
              - PUSH_TAGS=${TAGS}
              - touch .env && make docker-build docker-tag docker-push
            securityContext:
              privileged: true
