apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: hook
  labels:
    app: hook
  annotations:
    wave.pusher.com/update-on-config-change: "true"
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: hook
    spec:
      serviceAccountName: "hook"
      terminationGracePeriodSeconds: 180
      containers:
      - name: hook
        image: gcr.io/k8s-prow/hook:v20190403-92775d213
        imagePullPolicy: Always
        args:
        - --dry-run=false
        - --job-config-path=/etc/jobs
        ports:
          - name: http
            containerPort: 8888
        volumeMounts:
        - name: hmac
          mountPath: /etc/webhook
          readOnly: true
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: plugins
          mountPath: /etc/plugins
          readOnly: true
        - name: jobs
          mountPath: /etc/jobs
          readOnly: true
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8081
        initialDelaySeconds: 3
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: /healthz/ready
          port: 8081
        initialDelaySeconds: 10
        periodSeconds: 3
        timeoutSeconds: 600
      volumes:
      - name: hmac
        secret:
          secretName: hmac-token
      - name: oauth
        secret:
          secretName: oauth-token
      - name: config
        configMap:
          name: config
      - name: plugins
        configMap:
          name: plugins
      - name: jobs
        configMap:
          name: jobs
